### ISSUE TITLE
how do use your menu 

### ISSUE THREAD

**Issue by tacticalCoolGJ** [divinelemon/DivinelemonsCheatMenu#2]
how do i use your prodigy cheat menu

**Comment by divinelemon** [comment]
@tacticalCoolGJ Thanks for following me! I never got around to finishing this little project-- I stopped contributing to PMGH right before the major switch to `_` (before it was `hack`)-- which means that this project is outdated even if it worked, which it doesn't. Thanks for asking, though :)
